name: Deploy Blog

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: [vault-updated] # obsidian-default-vaultの `_published` が更新されたらdispatchされる

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hokori-log Repo
        uses: actions/checkout@v4
        with:
          path: hokori-log

      - name: Checkout obsidian-default-vault Repo (to temp location)
        uses: actions/checkout@v4
        with:
          repository: tachibanayu24/obsidian-default-vault
          path: vault-temp
          token: ${{ secrets.VAULT_ACCESS_TOKEN }}

      - name: Prepare content directory
        run: mkdir -p hokori-log/content

      - name: Copy published content
        run: |
          if [ -d "vault-temp/_published" ] && [ "$(ls -A vault-temp/_published)" ]; then
            cp -r vault-temp/_published/* hokori-log/content/
          else
            echo "Warning: vault-temp/_published directory is empty or does not exist."
          fi

      - name: Copy attachments to content root
        run: |
          if [ -d "vault-temp/_config/attachment" ] && [ "$(ls -A vault-temp/_config/attachment)" ]; then
            cp -r vault-temp/_config/attachment/* hokori-log/content/
          else
            echo "Info: vault-temp/_config/attachment directory is empty or does not exist."
          fi


      - name: Setup Node, Install, Build
        working-directory: hokori-log
        env:
          NODE_ENV: production
        run: |
          npm ci
          npx quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hokori-log/public
          cname: blog.tachibanayu24.com
